### ISSUE TITLE
depuracion del codigo

### ISSUE THREAD

**Issue by ajm14** [JoseManuelBravoDAW/JAVA2_ISSUES#1]
private static boolean deseaContinuar(){
		char caracter;
		//boolean continuar;
		do{
			caracter = Teclado.leerCaracter("Desea continuar?");
		}while (caracter != 's' && caracter != 'S' && caracter != 'n' && caracter != 'N');
		
		if (caracter == 's' || caracter == 'S'){
			//continuar = true;
			return true;
		} else 
			
				return false;
			
		//return continuar;
	}
}

esta linea se podria mejorar

**Comment by JoseManuelBravoDAW** [comment]
Lo tendre en cuenta, gracias

**Comment by ajm14** [comment]
ok

**Comment by JoseManuelBravoDAW** [comment]
Añado link al código:

https://github.com/JoseManuelBravoDAW/JAVA2_ISSUES/blob/master/PerimetroRectangulo#L32-L50
